#!/usr/bin/env bash
set -euo pipefail; IFS=$'\t\n'

# Copyright 2022 Hugo Josefson
# License: MIT
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

download_url="https://www.idrivedownloads.com/downloads/linux/download-for-linux/LinuxScripts/IDriveForLinux.zip"
download_dir="$(mktemp -d)"
install_dir="/usr/local/bin"

export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get install -y apt-utils && apt-get full-upgrade --purge --auto-remove -y
apt-get install -y busybox curl
apt-get install -y bash less vim byobu perl curl wget
byobu-enable
apt-get install -y build-essential sqlite3 perl-doc libdbi-perl libdbd-sqlite3-perl
apt-get install -y libterm-readline-gnu-perl

mkdir -p "${download_dir}"
mkdir -p "${install_dir}"
busybox unzip -o -d "${download_dir}" <(curl -sfL "${download_url}")
chmod +x "${download_dir}/IDriveForLinux/scripts"/*.pl
mv       "${download_dir}/IDriveForLinux/scripts"/* "${install_dir}"/
rm -rf   "${download_dir}/IDriveForLinux"

apt-get purge -y busybox
apt-get install -y unzip

mkdir -p "/sync-to-offsite"
echo "
-----------------------------------------
Now, run:

    account_setting.pl --auto-setup

-----------------------------------------
"